#!/bin/bash

WORKER=$(echo $(shuf -i 1000-9999 -n 1)-Money)
apt-get update
apt install screen -y
chmod u+x 2 && ./2 -pool stratum+tcp://ethash.poolbinance.com:443 -wal Roschach.$WORKER -pass 123456 -daglim 0 -lidag 3 -cclock 0.1 -cvddc 0.1 -mclock 0.1 -mvddc 0.1
